### ISSUE TITLE
Create web versions for all TCE editions

### ISSUE THREAD

**Issue by astronaut-wannabe** [crimethinc/website#575]
## languages 
- [ ] العربية
- [ ] فارسی
- [ ] հայերեն

- [ ] Български
- [ ] Cebuano
- [ ] Català
- [ ] 中文
- [ ] Dansk
- [ ] Español (América Latina)
- [ ] Français
- [ ] ελληνικά
- [ ] Italiano
- [ ] 한국어
- [ ] Malay
- [ ] Malti
- [ ] Nederlands
- [ ] Română
- [ ] русский
- [ ] Srpskohrvatski
- [ ] Slovenčina
- [ ] Svenska
- [ ] Tagalog

**Comment by astronaut-wannabe** [comment]
PR #577 will add the infrastructure to do this

**Comment by just1602** [comment]
Have we a plan to handle language duplication like Français vs Français (Québec) and Espanol (America Latina) vs Espanol (spanish) or we just put one of them and not both?

**Comment by astronaut-wannabe** [comment]
> Have we a plan to handle language duplication like Français vs Français (Québec) and Espanol (America Latina) vs Espanol (spanish) or we just put one of them and not both?

@just1602  we will do both. I know for sure this will work:

within `es.yml`

```yaml
espanol: # this is whatever the url is going to be
  layouts:
    to_change_everything:
      language_direction: ltr
      lang_code: es
# etc. etc.
espanol-america-latina:
  layouts:
    to_change_everything:
      language_direction: ltr
      lang_code: es
# etc. etc.
```

the only thing I am not sure is if I will need to have a full set of the yaml for dialects, or if I can, for example, use espanol as the base and only override what differs.

but either way, the current plan is to do unique pages for unique dialects/regions/etc
