### ISSUE TITLE
AccessDeniedAccess error on a "To Change Everything" image asset

### ISSUE THREAD

**Issue by astronaut-wannabe** [crimethinc/website#669]
## This asset: 
- https://cloudfront.crimethinc.com/tce/images/takeflight-phone-large.jpg

## is returning this error:
```
AccessDeniedAccess DeniedC921EDE5FFA063C4ooidtMhvJMIZjpDzFjntUcXLdPtza0wBnH35T+nQMxrfeefxaQIhYQvLdxuQgQB394uN3sngmyk=
```

## solution:

I think maybe the permissions in the CDN just need to be modified to make it publicly readable

## more context
this asset is used for tablet-sized devices with low dpi displays (which is probably why this has gone unnoticed)

tor browser seems like it spoofs your screen resolution to try to prevent fingerprinting, which is how I noticed this (the image doesn't load in tor browser)

#### here: 
* [app/assets/stylesheets/to_change_everything/_common.scss#L356-L363][0]
```scss

    #takeflight {
      width: 100%;
      background-image: url('https://cloudfront.crimethinc.com/tce/images/takeflight-phone-large.jpg');
      background-size: 100%;
      padding-bottom: 177%;
      background-position:center top;
      position: relative;
}
```
#### and here: 
* [app/assets/stylesheets/to_change_everything/_common.scss#L1141-L1148][1]
```scss
      #takeflight {
        width: 100%;
        background-image: url('https://cloudfront.crimethinc.com/tce/images/takeflight-phone-large.jpg');
        background-size: 100%;
        padding-bottom: 177%;
        background-position:center top;
        position: relative;
}
```

[0]:https://github.com/crimethinc/website/blob/master/app/assets/stylesheets/to_change_everything/_common.scss#L356-L363
[1]:https://github.com/crimethinc/website/blob/master/app/assets/stylesheets/to_change_everything/_common.scss#L1141-L1148
